# Generated by Django 4.1.4 on 2022-12-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hotelimages_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='Amenity_name',
            new_name='amenity_name',
        ),
    ]
